---
# tasks file for roles/snelson_redhat.ocp_images.rename
- name: Re-Tag Images
  command:
    argv:
      - podman
      - tag
      - "{{ src_registry_url }}{{ item }}"
      - "{{ dest_registry_url }}{{ item }}"
  delegate_to: localhost
  changed_when: true
  with_items:
    - "{{ docker_image_list_required }}"
    - "{{ docker_image_list_optional }}"
    - "{{ docker_image_list_s2i }}"
  tags:
    - ocp_images
    - rename_image
    - tag_image

- name: Re-Tag ose-node to major version
  command:
    argv:
      - podman
      - tag
      # - "{{ src_registry_url }}{{ item }}"
      # - "{{ dest_registry_url }}{{ item | map('regex_replace', '(.*):(.*)', ose_major_version ) }}"
      - "{{ src_registry_url }}openshift3/ose-node:v3.11.135"
      - "{{ dest_registry_url }}openshift3/ose-node:v3.11"
  delegate_to: localhost
  changed_when: true
  tags:
    - ocp_images
    - rename_major_image
    - tag_image

- name: Remove old Tag
  command:
    argv:
      - podman
      - rmi
      - "{{ src_registry_url }}{{ item }}"
  delegate_to: localhost
  when: ocp_image_delete == true
  changed_when: true
  with_items:
    - "{{ docker_image_list_required }}"
    - "{{ docker_image_list_optional }}"
    - "{{ docker_image_list_s2i }}"
  tags:
    - never
    - ocp_images
    - remove_image
